/**
 * Sidebar 採 autogenerated 模式：
 * - 新增 .md 檔到 docs/published/{分類}/ 後自動出現
 * - 各分類的 label / 排序 / 收合狀態由該資料夾下的 _category_.json 控制
 * - 個別文件順序可在 frontmatter 加 sidebar_position: N 控制
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  techNoteSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
